'use strict';
const UI={views:{},session:null,capturedBlob:null,capturedUrl:null,decodedQR:null,lastSavedId:null,currentDetail:null,recordsMode:'list',recordsAdminMode:false,recordsPageSize:25,recordsShown:25,deferredInstall:null};
const $=id=>document.getElementById(id);
const fmtDateTime=iso=>{try{return new Date(iso).toLocaleString();}catch{return iso||'—';}};
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function setMsg(el,msg,type=''){el.textContent=msg||'';el.className='message'+(type?' '+type:'');}
function showView(name){Object.values(UI.views).forEach(v=>v.classList.add('hidden'));UI.views[name].classList.remove('hidden');window.scrollTo({top:0,behavior:'instant'});}
function sessionUserText(){return UI.session?`${UI.session.user_code} · ${UI.session.full_name}`:'';}
function updateHeader(){UI.session=currentSession();$('userBadge').textContent=UI.session?sessionUserText():'';}
async function init(){UI.views={setup:$('setupView'),login:$('loginView'),dashboard:$('dashboardView'),scan:$('scanView'),success:$('successView'),records:$('recordsView'),detail:$('detailView'),admin:$('adminView')};await openDB();await ensureDefaultSettings();$('appTitle').textContent=await getSetting('app_name','Offline QR Capture');updateHeader();bindEvents();registerPWA();const users=await dbGetAll('users');if(!users.length){showView('setup');return;}if(UI.session){await openDashboard();}else showView('login');}
function bindEvents(){
 $('setupForm').addEventListener('submit',async e=>{e.preventDefault();setMsg($('setupMsg'),'Creating administrator...');try{if($('setupPassword').value!==$('setupPassword2').value)throw new Error('Passwords do not match.');await setSetting('device_code',$('setupDeviceCode').value.trim());await setSetting('device_name',$('setupDeviceName').value.trim());await setSetting('device_location',$('setupDeviceLocation').value.trim());await createLocalUser({user_code:$('setupCode').value,full_name:$('setupName').value,username:$('setupUsername').value,password:$('setupPassword').value,role:'admin'});setMsg($('setupMsg'),'Administrator created. Please sign in.','success');$('loginUsername').value=$('setupUsername').value.trim().toLowerCase();setTimeout(()=>showView('login'),500);}catch(err){setMsg($('setupMsg'),err.message,'error');}});
 $('loginForm').addEventListener('submit',async e=>{e.preventDefault();setMsg($('loginMsg'),'Checking local credentials...');try{UI.session=await loginLocal($('loginUsername').value,$('loginPassword').value);$('loginPassword').value='';updateHeader();await openDashboard();}catch(err){setMsg($('loginMsg'),err.message,'error');}});
 $('togglePassword').onclick=()=>{const p=$('loginPassword');p.type=p.type==='password'?'text':'password';$('togglePassword').textContent=p.type==='password'?'Show':'Hide';};
 $('logoutBtn').onclick=()=>{stopCamera();logoutLocal();UI.session=null;updateHeader();showView('login');};
 $('newScanBtn').onclick=startScanFlow;$('torchBtn').onclick=async()=>{try{const on=await setTorch(!CAMERA.torch);$('torchBtn').textContent=on?'Torch On':'Torch Off';}catch(e){alert(e.message);}};$('scanBackBtn').onclick=()=>{resetScan();openDashboard();};$('captureBtn').onclick=capturePhoto;$('retryBtn').onclick=startScanFlow;$('retryPhotoBtn').onclick=startScanFlow;$('okBtn').onclick=processPhoto;$('confirmQrBtn').onclick=completeCapture;
 $('viewRecordsBtn').onclick=()=>openRecords(false);$('recordsBackBtn').onclick=()=>UI.recordsAdminMode?openAdmin():openDashboard();$('listModeBtn').onclick=()=>{UI.recordsMode='list';renderRecords();};$('galleryModeBtn').onclick=()=>{UI.recordsMode='gallery';renderRecords();};['recordSearch','recordFrom','recordTo','recordSort','adminUserFilter'].forEach(id=>$(id)?.addEventListener('input',()=>{UI.recordsShown=25;renderRecords();}));$('loadMoreBtn').onclick=()=>{UI.recordsShown+=UI.recordsPageSize;renderRecords();};
 $('detailBackBtn').onclick=()=>openRecords(UI.recordsAdminMode);$('engineHoursBtn').onclick=updateEngineHours;$('successNewBtn').onclick=startScanFlow;$('successViewBtn').onclick=()=>openDetail(UI.lastSavedId);$('successDashBtn').onclick=openDashboard;
 $('exportMineBtn').onclick=async()=>{try{const n=await exportBackup({all:false,userId:UI.session.user_id,newOnly:true});if(!n){alert('No new records to export.');return;}alert(`New-record backup created with ${n} record(s). These records are now marked as exported.`);await refreshBackupReminder();}catch(e){alert(e.message);}};
 $('adminBtn').onclick=openAdmin;$('adminBackBtn').onclick=openDashboard;$('createUserForm').addEventListener('submit',createUserFromAdmin);$('saveSettingsBtn').onclick=saveAdminSettings;$('viewAllRecordsBtn').onclick=()=>openRecords(true);$('exportAllPendingBtn').onclick=async()=>{try{const n=await exportBackup({all:true,newOnly:true});alert(n?`Exported ${n} pending record(s) from all users.`:'No pending records to export.');}catch(e){alert(e.message);}};$('deleteRecordBtn').onclick=deleteCurrentRecord;
 window.addEventListener('pagehide',stopCamera);window.addEventListener('beforeunload',stopCamera);
}
async function openDashboard(){UI.session=currentSession();if(!UI.session){showView('login');return;}updateHeader();$('dashUserCode').textContent=UI.session.user_code;$('dashName').textContent=UI.session.full_name;$('dashRole').textContent=UI.session.role;$('dashDevice').textContent=`${await getSetting('device_code','')} · ${await getSetting('device_name','')}`;$('versionText').textContent=`App ${APP_VERSION} · DB ${DB_SCHEMA_VERSION} · QR ${QR_SCHEMA_VERSION}`;$('scanUserCode').textContent=UI.session.user_code;$('adminBtn').classList.toggle('hidden',UI.session.role!=='admin');const mine=await dbGetAllByIndex('captures','user_id',UI.session.user_id);const today=new Date().toISOString().slice(0,10);$('todayCount').textContent=mine.filter(r=>r.capture_date===today).length;$('userCount').textContent=mine.length;await refreshStorage();await refreshBackupReminder();showView('dashboard');}
async function refreshStorage(){try{const est=await navigator.storage?.estimate?.();if(est&&est.usage!=null){const ratio=est.quota?est.usage/est.quota:0;$('storageText').textContent=formatBytes(est.usage)+(est.quota?` / ${formatBytes(est.quota)}`:'');if(ratio>=Number(await getSetting('storage_warning_ratio',.70)))$('storageText').textContent+=' ⚠';}else $('storageText').textContent='Local';}catch{$('storageText').textContent='Local';}}
function formatBytes(n){if(n<1024)return`${n} B`;if(n<1024**2)return`${(n/1024).toFixed(1)} KB`;if(n<1024**3)return`${(n/1024**2).toFixed(1)} MB`;return`${(n/1024**3).toFixed(2)} GB`;}
async function refreshBackupReminder(){const last=await getSetting('last_backup_at',null);const el=$('backupReminder');if(!last){el.classList.remove('hidden');el.innerHTML='<strong>Backup Recommended</strong><p>No backup has been recorded on this device yet.</p>';return;}const days=(Date.now()-new Date(last).getTime())/86400000;if(days>=7){el.classList.remove('hidden');el.innerHTML=`<strong>Backup Recommended</strong><p>Last backup was about ${Math.floor(days)} day(s) ago.</p>`;}else el.classList.add('hidden');}
async function startScanFlow(){if(!UI.session)return;resetScan(false);showView('scan');setMsg($('scanMsg'),'Opening camera...');try{const torch=await startCamera($('cameraVideo'));$('torchBtn').classList.toggle('hidden',!torch);$('torchBtn').textContent='Torch Off';$('cameraVideo').classList.remove('hidden');$('previewImage').classList.add('hidden');$('captureBtn').classList.remove('hidden');setMsg($('scanMsg'),'');}catch(e){setMsg($('scanMsg'),e.message,'error');}}
function resetScan(navigate=false){stopCamera();UI.capturedBlob=null;UI.decodedQR=null;if(UI.capturedUrl){URL.revokeObjectURL(UI.capturedUrl);UI.capturedUrl=null;}$('previewImage').src='';$('previewImage').classList.add('hidden');$('cameraVideo').classList.remove('hidden');$('captureBtn').classList.remove('hidden');$('torchBtn').classList.add('hidden');$('retryBtn').classList.add('hidden');$('okBtn').classList.add('hidden');$('qrReview').classList.add('hidden');$('processPanel').classList.add('hidden');setMsg($('scanMsg'),'');if(navigate)openDashboard();}
async function capturePhoto(){try{$('captureBtn').disabled=true;const max=Number(await getSetting('image_max_width',1600));const q=Number(await getSetting('jpeg_quality',.8));UI.capturedBlob=await captureCompressed($('cameraVideo'),$('captureCanvas'),max,q);stopCamera();UI.capturedUrl=URL.createObjectURL(UI.capturedBlob);$('previewImage').src=UI.capturedUrl;$('previewImage').classList.remove('hidden');$('cameraVideo').classList.add('hidden');$('captureBtn').classList.add('hidden');$('retryBtn').classList.remove('hidden');$('okBtn').classList.remove('hidden');setMsg($('scanMsg'),'Review the photograph. Press Retry to take another or OK to read both QR codes.','success');}catch(e){setMsg($('scanMsg'),e.message,'error');}finally{$('captureBtn').disabled=false;}}
async function processPhoto(){if(!UI.capturedBlob)return;toggleScanButtons(true);$('processPanel').classList.remove('hidden');$('processText').textContent='Reading QR codes locally...';setMsg($('scanMsg'),'');try{UI.decodedQR=await detectTwoQRCodes(UI.capturedBlob);$('qr1Review').value=UI.decodedQR.labelA.raw;$('qr2Review').value=UI.decodedQR.labelB.raw;$('processPanel').classList.add('hidden');$('qrReview').classList.remove('hidden');$('retryBtn').classList.add('hidden');$('okBtn').classList.add('hidden');}catch(e){$('processPanel').classList.add('hidden');setMsg($('scanMsg'),e.message,'error');$('retryBtn').classList.remove('hidden');$('okBtn').classList.remove('hidden');}finally{toggleScanButtons(false);}}
function toggleScanButtons(disabled){['captureBtn','retryBtn','okBtn','confirmQrBtn','retryPhotoBtn'].forEach(id=>{const el=$(id);if(el)el.disabled=disabled;});}
async function getGPS(){if(!navigator.geolocation)throw new Error('Location is not supported on this device.');return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,gps_status:'success'}),e=>reject(new Error(e.code===1?'Location permission was denied.':e.code===2?'Location is currently unavailable.':'Location request timed out.')),{enableHighAccuracy:true,timeout:15000,maximumAge:0}));}
async function completeCapture(){if(!UI.capturedBlob||!UI.decodedQR)return;toggleScanButtons(true);$('qrReview').classList.add('hidden');$('processPanel').classList.remove('hidden');$('processText').textContent='Getting GPS location...';try{let gps={latitude:null,longitude:null,accuracy:null,gps_status:'failed'};const required=Boolean(await getSetting('gps_required',true));try{gps=await getGPS();}catch(e){if(required)throw new Error(`${e.message} GPS is required, so the record was not saved.`);gps.gps_error=e.message;}$('processText').textContent='Saving locally...';const now=new Date(),recordId=crypto.randomUUID(),deviceCode=await getSetting('device_code','DEVICE'),seq=String((await dbGetAll('captures')).length+1).padStart(6,'0');const imageHash=await sha256Hex(UI.capturedBlob);const A=UI.decodedQR.labelA,B=UI.decodedQR.labelB;const record={record_id:recordId,display_record_id:`${deviceCode}-${localDate(now).replaceAll('-','')}-${seq}`,device_uuid:await getSetting('device_uuid',''),device_code:deviceCode,device_name:await getSetting('device_name',''),device_location:await getSetting('device_location',''),user_id:UI.session.user_id,user_code:UI.session.user_code,username:UI.session.username,full_name:UI.session.full_name,label_a_raw:A.raw,bottle_uuid:A.bottle_uuid,rack:A.rack,shelf:A.shelf,crate:A.crate,x:A.x,y:A.y,future:A.future,label_b_raw:B.raw,sticker_uuid:B.sticker_uuid,aircraft_tail_no:B.aircraft_tail_no,engine_no:B.engine_no,engine_side:B.engine_side,oil_spec:await getSetting('oil_spec','Turbonic210A'),engine_hours:null,engine_hours_entered_at:null,engine_hours_entered_by:null,capture_date:localDate(now),capture_time:localTime(now),captured_at:localIso(now),timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'',latitude:gps.latitude,longitude:gps.longitude,accuracy:gps.accuracy,gps_status:gps.gps_status,gps_error:gps.gps_error||null,...(await saveImageToLocalStorage(recordId,UI.capturedBlob)),image_type:UI.capturedBlob.type||'image/jpeg',image_sha256:imageHash,export_status:'pending',exported_at:null,export_batch_id:null,pseudo_deleted:false,deleted_at:null,deleted_by:null,app_version:APP_VERSION,db_schema_version:DB_SCHEMA_VERSION,qr_schema_version:QR_SCHEMA_VERSION,created_at:new Date().toISOString()};const dupe=await recentDuplicate(record);if(dupe&&!confirm('This same QR combination was captured recently. Save anyway?')){throw new Error('Save cancelled.');}await dbAdd('captures',record);UI.lastSavedId=record.record_id;UI.currentDetail=record;$('processPanel').classList.add('hidden');renderSuccess(record);stopCamera();showView('success');UI.capturedBlob=null;UI.decodedQR=null;}catch(e){$('processPanel').classList.add('hidden');$('qrReview').classList.remove('hidden');setMsg($('scanMsg'),e.message,'error');}finally{toggleScanButtons(false);}}
function localDate(d){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return`${y}-${m}-${day}`;}function localTime(d){return`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}:${String(d.getSeconds()).padStart(2,'0')}`;}function localIso(d){const off=-d.getTimezoneOffset(),sign=off>=0?'+':'-',hh=String(Math.floor(Math.abs(off)/60)).padStart(2,'0'),mm=String(Math.abs(off)%60).padStart(2,'0');return`${localDate(d)}T${localTime(d)}${sign}${hh}:${mm}`;}
async function recentDuplicate(r){const mine=await dbGetAllByIndex('captures','user_id',r.user_id);const cutoff=Date.now()-5*60000;return mine.find(x=>x.label_a_raw===r.label_a_raw&&x.label_b_raw===r.label_b_raw&&new Date(x.captured_at).getTime()>=cutoff);}
function renderSuccess(r){$('successDetails').innerHTML=detailHtml(r,false);}
async function openRecords(adminMode=false){UI.recordsAdminMode=adminMode&&UI.session?.role==='admin';UI.recordsShown=25;$('recordsHeading').textContent=UI.recordsAdminMode?'All Local Records':'My Records';$('recordsSub').textContent=UI.recordsAdminMode?'Administrator view across all local users.':`User ID: ${UI.session.user_code}`;$('adminUserFilterWrap').classList.toggle('hidden',!UI.recordsAdminMode);if(UI.recordsAdminMode){const users=await dbGetAll('users');$('adminUserFilter').innerHTML='<option value="">All users</option>'+users.map(u=>`<option value="${esc(u.id)}">${esc(u.user_code)} - ${esc(u.full_name)}</option>`).join('');}showView('records');await renderRecords();}
async function filteredRecords(){let rows=(await dbGetAll('captures')).filter(r=>!r.pseudo_deleted);if(!UI.recordsAdminMode)rows=rows.filter(r=>r.user_id===UI.session.user_id);else if($('adminUserFilter').value)rows=rows.filter(r=>r.user_id===$('adminUserFilter').value);const q=$('recordSearch').value.trim().toLowerCase(),from=$('recordFrom').value,to=$('recordTo').value;if(q)rows=rows.filter(r=>String(r.label_a_raw).toLowerCase().includes(q)||String(r.label_b_raw).toLowerCase().includes(q)||String(r.bottle_uuid).toLowerCase().includes(q)||String(r.sticker_uuid).toLowerCase().includes(q)||String(r.user_code).toLowerCase().includes(q));if(from)rows=rows.filter(r=>r.capture_date>=from);if(to)rows=rows.filter(r=>r.capture_date<=to);rows.sort((a,b)=>$('recordSort').value==='asc'?String(a.captured_at).localeCompare(String(b.captured_at)):String(b.captured_at).localeCompare(String(a.captured_at)));return rows;}
async function renderRecords(){const all=await filteredRecords();const rows=all.slice(0,UI.recordsShown),list=$('recordsList');list.className='records-list'+(UI.recordsMode==='gallery'?' gallery':'');list.innerHTML='';for(const r of rows){const card=document.createElement('article');card.className='record';card.dataset.id=r.record_id;const url=URL.createObjectURL(await getRecordImageBlob(r));card.innerHTML=`<div class="record-row"><img src="${url}" alt="Capture thumbnail"><div class="record-meta"><strong>${esc(r.capture_date)} · ${esc(r.capture_time)}</strong><p>${esc(r.user_code)} · ${esc(r.full_name)}</p><p><b>Label A:</b> ${esc(r.label_a_raw)}</p><p><b>Label B:</b> ${esc(r.label_b_raw)}</p><p><b>Device:</b> ${esc(r.device_code)}</p><p><b>Export:</b> ${esc(r.export_status||'pending')}</p><p><b>GPS:</b> ${r.gps_status==='success'?'Captured':'Unavailable'}</p></div></div>`;card.onclick=()=>{URL.revokeObjectURL(url);openDetail(r.record_id);};list.appendChild(card);}if(!rows.length)list.innerHTML='<p class="muted">No matching records.</p>';$('loadMoreBtn').classList.toggle('hidden',UI.recordsShown>=all.length);$('recordsMsg').textContent=`Showing ${rows.length} of ${all.length} record(s).`;}
async function openDetail(id){const r=await dbGet('captures',id);if(!r){alert('Record not found.');return;}UI.currentDetail=r;showView('detail');if($('detailImage').dataset.url)URL.revokeObjectURL($('detailImage').dataset.url);const url=URL.createObjectURL(await getRecordImageBlob(r));$('detailImage').src=url;$('detailImage').dataset.url=url;$('detailMeta').innerHTML=detailHtml(r,true);const canDelete=UI.session.role==='admin'||Boolean(await getSetting('allow_user_delete',false));$('deleteRecordBtn').classList.toggle('hidden',!canDelete);}
function detailHtml(r,full=true){const rows=[['Reference',r.display_record_id],['Collector User ID',r.user_code],['Collector Name',r.full_name],['Device',`${r.device_code||''} · ${r.device_name||''}`],['Label A',r.label_a_raw],['Bottle UUID',r.bottle_uuid],['Rack',r.rack],['Shelf',r.shelf],['Crate',r.crate],['X',r.x],['Y',r.y],['Future',r.future],['Label B',r.label_b_raw],['Sticker UUID',r.sticker_uuid],['Aircraft Tail No',r.aircraft_tail_no],['Engine No',r.engine_no],['Engine Side',r.engine_side],['Oil Spec',r.oil_spec],['Engine Hours',r.engine_hours??'Not entered'],['Date',r.capture_date],['Time',r.capture_time],['Timestamp',r.captured_at],['Timezone',r.timezone],['GPS Status',r.gps_status],['Latitude',r.latitude??'—'],['Longitude',r.longitude??'—'],['GPS Accuracy',r.accuracy!=null?`${Math.round(r.accuracy)} m`:'—'],['Image SHA-256',r.image_sha256],['Export Status',r.export_status||'pending'],['Record ID',r.record_id],['Versions',`App ${r.app_version||APP_VERSION} · DB ${r.db_schema_version||DB_SCHEMA_VERSION} · QR ${r.qr_schema_version||QR_SCHEMA_VERSION}`]];return rows.map(([k,v])=>`<div class="detail-row"><strong>${esc(k)}</strong><span>${esc(v)}</span></div>`).join('');}
async function updateEngineHours(){if(!UI.currentDetail)return;const v=prompt('Enter Engine Hours (this may be added later at the storage lab):',UI.currentDetail.engine_hours||'');if(v===null)return;const val=v.trim();if(!val){alert('Engine Hours cannot be blank.');return;}UI.currentDetail.engine_hours=val;UI.currentDetail.engine_hours_entered_at=new Date().toISOString();UI.currentDetail.engine_hours_entered_by=UI.session.user_id;await dbPut('captures',UI.currentDetail);alert('Engine Hours saved.');await openDetail(UI.currentDetail.record_id);}
async function deleteCurrentRecord(){if(!UI.currentDetail)return;if(!confirm('Mark this record as deleted? The data will be retained locally for audit.'))return;UI.currentDetail.pseudo_deleted=true;UI.currentDetail.deleted_at=new Date().toISOString();UI.currentDetail.deleted_by=UI.session.user_id;await dbPut('captures',UI.currentDetail);UI.currentDetail=null;alert('Record pseudo-deleted and retained for audit.');openRecords(UI.recordsAdminMode);}
async function openAdmin(){if(UI.session?.role!=='admin'){alert('Administrator required.');return;}showView('admin');$('gpsRequired').value=(await getSetting('gps_required',true))?'1':'0';$('imageMaxWidth').value=await getSetting('image_max_width',1600);$('jpegQuality').value=await getSetting('jpeg_quality',.8);$('allowUserDelete').value=(await getSetting('allow_user_delete',false))?'1':'0';$('deviceCode').value=await getSetting('device_code','');$('deviceName').value=await getSetting('device_name','');$('deviceLocation').value=await getSetting('device_location','');$('oilSpec').value=await getSetting('oil_spec','Turbonic210A');await renderUsers();}
async function createUserFromAdmin(e){e.preventDefault();setMsg($('adminMsg'),'Creating user...');try{await createLocalUser({user_code:$('newUserCode').value,full_name:$('newUserName').value,username:$('newUsername').value,password:$('newUserPassword').value,role:$('newUserRole').value});e.target.reset();setMsg($('adminMsg'),'User created successfully.','success');await renderUsers();}catch(err){setMsg($('adminMsg'),err.message,'error');}}
async function renderUsers(){const users=await dbGetAll('users');users.sort((a,b)=>a.full_name.localeCompare(b.full_name));$('usersTable').innerHTML=users.map(u=>`<tr><td>${esc(u.user_code)}</td><td>${esc(u.full_name)}</td><td>${esc(u.username)}</td><td>${esc(u.role)}</td><td>${u.active?'Active':'Inactive'}</td><td><button class="button secondary" onclick="adminResetPassword('${u.id}')">Reset Password</button> <button class="button ${u.active?'danger':'secondary'}" onclick="adminToggleUser('${u.id}')">${u.active?'Deactivate':'Activate'}</button></td></tr>`).join('');}
window.adminResetPassword=async id=>{const p=prompt('Enter a new password (minimum 8 characters):');if(p===null)return;const p2=prompt('Enter the same password again:');if(p!==p2){alert('Passwords do not match.');return;}try{await resetLocalPassword(id,p);alert('Password reset successfully.');}catch(e){alert(e.message);}};
window.adminToggleUser=async id=>{const u=await dbGet('users',id);if(!u)return;if(u.id===UI.session.user_id&&u.active){alert('You cannot deactivate the currently logged-in administrator.');return;}u.active=!u.active;u.updated_at=new Date().toISOString();await dbPut('users',u);await renderUsers();};
async function saveAdminSettings(){try{await setSetting('gps_required',$('gpsRequired').value==='1');await setSetting('image_max_width',Math.max(640,Math.min(4096,Number($('imageMaxWidth').value)||1600)));await setSetting('jpeg_quality',Math.max(.5,Math.min(.95,Number($('jpegQuality').value)||.8)));await setSetting('allow_user_delete',$('allowUserDelete').value==='1');await setSetting('device_code',$('deviceCode').value.trim());await setSetting('device_name',$('deviceName').value.trim());await setSetting('device_location',$('deviceLocation').value.trim());await setSetting('oil_spec',$('oilSpec').value.trim());setMsg($('adminMsg'),'Settings saved locally.','success');}catch(e){setMsg($('adminMsg'),e.message,'error');}}
function registerPWA(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();UI.deferredInstall=e;$('installBtn').classList.remove('hidden');});$('installBtn').onclick=async()=>{if(!UI.deferredInstall){alert('Use your browser menu and choose Add to Home Screen / Install App.');return;}UI.deferredInstall.prompt();await UI.deferredInstall.userChoice;UI.deferredInstall=null;$('installBtn').classList.add('hidden');};window.addEventListener('appinstalled',()=>{$('installBtn').classList.add('hidden');});}
document.addEventListener('DOMContentLoaded',()=>init().catch(e=>{document.body.innerHTML=`<main class="shell"><section class="card narrow"><h1>Application Error</h1><p>${esc(e.message)}</p></section></main>`;}));
